import { Plugin } from 'vue';

import BaseButton from './components/BaseButton/index.vue';
import BaseCheckbox from './components/BaseCheckbox/index.vue';
import FormFieldCheckbox from './components/FormFieldCheckbox/index.vue';
import FormField from './components/FormField/index.vue';
import FormFieldError from './components/FormFieldError/index.vue';
import BaseInput from './components/BaseInput/index.vue';
import BaseTextArea from './components/BaseTextArea/index.vue';
import InputLabel from './components/InputLabel/index.vue';
import PageTitle from './components/PageTitle/index.vue';
import Spinner from './components/Spinner/index.vue';
import SvgIcon from './components/SvgIcon';
import Table from './components/Table/index.vue';
import TableCell from './components/Table/components/Cell.vue';
import FormGroup from './components/FormGroup.vue';
import FileInput from './components/FileInput/index.vue';
import FormFieldFileInput from './components/FormFieldFileInput/index.vue';
import NumberInput from './components/NumberInput/index.vue';
import FormFieldNumberInput from './components/FormFieldNumberInput/index.vue';
import FormFieldColorInput from './components/FormFieldColorInput/index.vue';
import FormFieldRichTextInput from './components/FormFieldRichTextInput/index.vue';
import BaseRichTextInput from './components/BaseRichTextInput/index.vue';
import MultiSelect from './components/MultiSelect/index.vue';
import FormFieldMultiSelect from './components/FormFieldMultiSelect/index.vue';
import FormFieldUrlAliasInput from './components/FormFieldUrlAliasInput';
import { ToastProvider } from './components/Toast';
import NavigationGrid from './components/NavigationGrid/index.vue';
import LoadableImage from './components/LoadableImage/index.vue';
import DropdownMenu from './components/DropdownMenu/index.vue';
import BaseSelect from './components/BaseSelect/index.vue';
import FormFieldSelect from './components/FormFieldSelect/index.vue';
import FormFieldSingleSelect from './components/FormFieldSingleSelect/index.vue';
import TabList from './components/TabList';
import ColorInput from './components/ColorInput';
import ButtonField from './components/ButtonField';
import DateTimeInput from './components/DateTimeInput';
import MapField from './components/MapField';
import ShortCodeConstructor from './components/ShortCodeConstructor';

export const AdminUiPlugin: Plugin = (app) => {
  app.component('base-button', BaseButton);
  app.component('base-checkbox', BaseCheckbox);
  app.component('base-input', BaseInput);
  app.component('base-select', BaseSelect);
  app.component('base-table', Table);
  app.component('base-table-cell', TableCell);
  app.component('base-textarea', BaseTextArea);
  app.component('base-rich-text-input', BaseRichTextInput);
  app.component('base-file-input', FileInput);
  app.component('base-number-input', NumberInput);
  app.component('base-color-input', ColorInput);

  app.component('form-group', FormGroup);
  app.component('form-field', FormField);
  app.component('form-field-checkbox', FormFieldCheckbox);
  app.component('form-field-select', FormFieldSelect);
  app.component('form-field-error', FormFieldError);
  app.component('form-field-rich-text-input', FormFieldRichTextInput);
  app.component('form-field-file-input', FormFieldFileInput);
  app.component('form-field-color-input', FormFieldColorInput);
  app.component('form-field-number-input', FormFieldNumberInput);
  app.component('form-field-multi-select', FormFieldMultiSelect);
  app.component('form-field-single-select', FormFieldSingleSelect);
  app.component('form-field-url-alias-input', FormFieldUrlAliasInput);

  app.component('multi-select', MultiSelect);
  app.component('input-label', InputLabel);
  app.component('page-title', PageTitle);
  app.component('spinner', Spinner);
  app.component('svg-icon', SvgIcon);
  app.component('toast-provider', ToastProvider);
  app.component('navigation-grid', NavigationGrid);
  app.component('loadable-image', LoadableImage);
  app.component('dropdown-menu', DropdownMenu);
  app.component('tab-list', TabList);
  app.component('button-field', ButtonField);
  app.component('map-field', MapField);
  app.component('date-time-input', DateTimeInput);
  app.component('short-code-constructor', ShortCodeConstructor);
};
